import { Router } from 'express';
import { z } from 'zod';
import { pool } from './db/pool.js';

export const actionPlanApi = Router();
const uuid=z.string().uuid(),status=z.enum(['planned','in_progress','completed','cancelled']),priority=z.enum(['low','medium','high']);
const input=z.object({diagnosticId:uuid,problem:z.string().trim().min(1).max(5000),proposedAction:z.string().trim().min(1).max(5000),priority,responsible:z.string().trim().min(1).max(180),status:status.default('planned'),notes:z.string().trim().max(5000).nullable().optional()});
const validation=(error:unknown,res:any,next:any)=>error instanceof z.ZodError?res.status(400).json({error:'Verifique os campos obrigatórios do plano de ação.',fields:error.flatten().fieldErrors}):next(error);

actionPlanApi.get('/companies/:companyId/action-plans',async(req,res,next)=>{try{const companyId=uuid.parse(req.params.companyId);const {rows}=await pool.query(`SELECT ap.*,d.name diagnostic_name,(ap.due_date<current_date AND ap.status NOT IN ('completed','cancelled')) overdue FROM action_plans ap JOIN diagnostics d ON d.id=ap.diagnostic_id WHERE ap.company_id=$1 ORDER BY (ap.due_date<current_date AND ap.status NOT IN ('completed','cancelled')) DESC,CASE ap.priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,ap.due_date,ap.created_at DESC`,[companyId]);res.json(rows)}catch(e){validation(e,res,next)}});
actionPlanApi.get('/companies/:companyId/action-plans/:id',async(req,res,next)=>{try{const companyId=uuid.parse(req.params.companyId),planId=uuid.parse(req.params.id);const {rows}=await pool.query(`SELECT ap.*,d.name diagnostic_name,(ap.due_date<current_date AND ap.status NOT IN ('completed','cancelled')) overdue FROM action_plans ap JOIN diagnostics d ON d.id=ap.diagnostic_id WHERE ap.company_id=$1 AND ap.id=$2`,[companyId,planId]);if(!rows[0])return res.status(404).json({error:'Plano de ação não encontrado.'});res.json(rows[0])}catch(e){validation(e,res,next)}});
actionPlanApi.post('/companies/:companyId/action-plans',async(req,res,next)=>{try{const companyId=uuid.parse(req.params.companyId),v=input.parse(req.body);const diagnostic=await pool.query('SELECT 1 FROM diagnostics WHERE id=$1 AND company_id=$2',[v.diagnosticId,companyId]);if(!diagnostic.rowCount)return res.status(400).json({error:'O diagnóstico selecionado não pertence a esta empresa.'});const {rows}=await pool.query(`INSERT INTO action_plans(company_id,diagnostic_id,problem,proposed_action,priority,responsible,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[companyId,v.diagnosticId,v.problem,v.proposedAction,v.priority,v.responsible,v.status,v.notes??null]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
actionPlanApi.put('/companies/:companyId/action-plans/:id',async(req,res,next)=>{try{const companyId=uuid.parse(req.params.companyId),planId=uuid.parse(req.params.id),v=input.parse(req.body);const diagnostic=await pool.query('SELECT 1 FROM diagnostics WHERE id=$1 AND company_id=$2',[v.diagnosticId,companyId]);if(!diagnostic.rowCount)return res.status(400).json({error:'O diagnóstico selecionado não pertence a esta empresa.'});const {rows}=await pool.query(`UPDATE action_plans SET diagnostic_id=$3,problem=$4,proposed_action=$5,priority=$6,responsible=$7,status=$8,notes=$9,updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING *`,[planId,companyId,v.diagnosticId,v.problem,v.proposedAction,v.priority,v.responsible,v.status,v.notes??null]);if(!rows[0])return res.status(404).json({error:'Plano de ação não encontrado.'});res.json(rows[0])}catch(e){validation(e,res,next)}});
actionPlanApi.patch('/companies/:companyId/action-plans/:id/status',async(req,res,next)=>{try{const companyId=uuid.parse(req.params.companyId),planId=uuid.parse(req.params.id),value=status.parse(req.body.status);const {rows}=await pool.query('UPDATE action_plans SET status=$3,updated_at=now() WHERE id=$1 AND company_id=$2 RETURNING *',[planId,companyId,value]);if(!rows[0])return res.status(404).json({error:'Plano de ação não encontrado.'});res.json(rows[0])}catch(e){validation(e,res,next)}});
actionPlanApi.delete('/companies/:companyId/action-plans/:id',async(req,res,next)=>{try{const companyId=uuid.parse(req.params.companyId),planId=uuid.parse(req.params.id);const result=await pool.query('DELETE FROM action_plans WHERE id=$1 AND company_id=$2',[planId,companyId]);if(!result.rowCount)return res.status(404).json({error:'Plano de ação não encontrado.'});res.status(204).end()}catch(e){validation(e,res,next)}});
