import { Router } from 'express';
import { z } from 'zod';
import { pool } from './db/pool.js';

export const adminApi = Router();
const id = z.string().uuid();
const bool = z.boolean();
const text = z.string().trim().min(1).max(5000);
const optionalText = z.string().trim().max(5000).nullable().optional();
const parse = <S extends z.ZodTypeAny>(schema:S, value:unknown):z.output<S> => schema.parse(value);
const validation = (error:unknown, res:any, next:any) => error instanceof z.ZodError
  ? res.status(400).json({error:'Dados inválidos.',fields:error.flatten().fieldErrors}) : next(error);

const companySchema=z.object({name:text.max(180),tradeName:optionalText,approximateEmployeeCount:z.number().int().nonnegative().nullable().optional(),notes:optionalText,active:bool.default(true)});
adminApi.get('/companies',async(_req,res,next)=>{try{const {rows}=await pool.query(`SELECT c.*,count(d.id)::int diagnostic_count FROM companies c LEFT JOIN diagnostics d ON d.company_id=c.id GROUP BY c.id ORDER BY c.active DESC,c.name`);res.json(rows)}catch(e){next(e)}});
adminApi.post('/companies',async(req,res,next)=>{try{const v=parse(companySchema,req.body),{rows}=await pool.query(`INSERT INTO companies(name,trade_name,approximate_employee_count,notes,active) VALUES($1,$2,$3,$4,$5) RETURNING *`,[v.name,v.tradeName??null,v.approximateEmployeeCount??null,v.notes??null,v.active]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.get('/companies/:id',async(req,res,next)=>{try{const companyId=id.parse(req.params.id);const [company,diagnostics]=await Promise.all([pool.query('SELECT * FROM companies WHERE id=$1',[companyId]),pool.query('SELECT * FROM diagnostics WHERE company_id=$1 ORDER BY created_at DESC',[companyId])]);if(!company.rows[0])return res.status(404).json({error:'Empresa não encontrada.'});res.json({...company.rows[0],diagnostics:diagnostics.rows})}catch(e){validation(e,res,next)}});
adminApi.put('/companies/:id',async(req,res,next)=>{try{const companyId=id.parse(req.params.id),v=parse(companySchema,req.body),{rows}=await pool.query(`UPDATE companies SET name=$2,trade_name=$3,approximate_employee_count=$4,notes=$5,active=$6,updated_at=now() WHERE id=$1 RETURNING *`,[companyId,v.name,v.tradeName??null,v.approximateEmployeeCount??null,v.notes??null,v.active]);if(!rows[0])return res.status(404).json({error:'Empresa não encontrada.'});res.json(rows[0])}catch(e){validation(e,res,next)}});

const diagnosticSchema=z.object({companyId:id,name:text.max(180),description:optionalText,status:z.enum(['draft','active','collecting','analysis','completed','archived']).default('draft'),startsOn:z.string().date().nullable().optional(),endsOn:z.string().date().nullable().optional(),expectedInterviewCount:z.number().int().nonnegative().nullable().optional(),favorableThreshold:z.number().min(0).max(100).default(75),criticalThreshold:z.number().min(0).max(100).default(60),minimumSampleSize:z.number().int().min(3).default(5),notes:optionalText}).refine(v=>!v.startsOn||!v.endsOn||v.endsOn>=v.startsOn,{message:'O fim deve ser posterior ao início.',path:['endsOn']});
adminApi.post('/diagnostics',async(req,res,next)=>{try{const v=parse(diagnosticSchema,req.body),{rows}=await pool.query(`INSERT INTO diagnostics(company_id,name,description,status,starts_on,ends_on,expected_interview_count,favorable_threshold,critical_threshold,minimum_sample_size,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[v.companyId,v.name,v.description??null,v.status,v.startsOn??null,v.endsOn??null,v.expectedInterviewCount??null,v.favorableThreshold,v.criticalThreshold,v.minimumSampleSize,v.notes??null]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.put('/diagnostics/:id',async(req,res,next)=>{try{const diagnosticId=id.parse(req.params.id),v=parse(diagnosticSchema,req.body),{rows}=await pool.query(`UPDATE diagnostics SET company_id=$2,name=$3,description=$4,status=$5,starts_on=$6,ends_on=$7,expected_interview_count=$8,favorable_threshold=$9,critical_threshold=$10,minimum_sample_size=$11,notes=$12,updated_at=now() WHERE id=$1 RETURNING *`,[diagnosticId,v.companyId,v.name,v.description??null,v.status,v.startsOn??null,v.endsOn??null,v.expectedInterviewCount??null,v.favorableThreshold,v.criticalThreshold,v.minimumSampleSize,v.notes??null]);if(!rows[0])return res.status(404).json({error:'Diagnóstico não encontrado.'});res.json(rows[0])}catch(e){validation(e,res,next)}});

adminApi.get('/diagnostics/:id/configuration',async(req,res,next)=>{try{const diagnosticId=id.parse(req.params.id);const diag=await pool.query(`SELECT d.*,c.name company_name FROM diagnostics d JOIN companies c ON c.id=d.company_id WHERE d.id=$1`,[diagnosticId]);if(!diag.rows[0])return res.status(404).json({error:'Diagnóstico não encontrado.'});const companyId=diag.rows[0].company_id;const [departments,positions,people,categories,lcod]=await Promise.all([
 pool.query('SELECT * FROM departments WHERE company_id=$1 ORDER BY sort_order,name',[companyId]),
 pool.query('SELECT * FROM positions WHERE company_id=$1 ORDER BY sort_order,name',[companyId]),
 pool.query(`SELECT p.*,coalesce(json_agg(pd.department_id) FILTER(WHERE pd.department_id IS NOT NULL),'[]') department_ids,(dp.person_id IS NOT NULL) linked FROM people p LEFT JOIN people_departments pd ON pd.person_id=p.id LEFT JOIN diagnostic_people dp ON dp.person_id=p.id AND dp.diagnostic_id=$2 WHERE p.company_id=$1 GROUP BY p.id,dp.person_id ORDER BY p.role,p.name`,[companyId,diagnosticId]),
 pool.query(`SELECT c.*,count(q.id)::int question_count FROM categories c LEFT JOIN questions q ON q.category_id=c.id WHERE c.diagnostic_id=$1 GROUP BY c.id ORDER BY c.sort_order,c.name`,[diagnosticId]),
 pool.query(`SELECT lc.*,coalesce(json_agg(json_build_object('id',lt.id,'name',lt.name,'description',lt.description,'active',lt.active,'sort_order',lt.sort_order) ORDER BY lt.sort_order) FILTER(WHERE lt.id IS NOT NULL),'[]') topics FROM lcod_categories lc LEFT JOIN lcod_topics lt ON lt.lcod_category_id=lc.id WHERE lc.diagnostic_id=$1 GROUP BY lc.id ORDER BY lc.sort_order,lc.name`,[diagnosticId])
]);res.json({diagnostic:diag.rows[0],departments:departments.rows,positions:positions.rows,people:people.rows,categories:categories.rows,lcod:lcod.rows})}catch(e){validation(e,res,next)}});

const departmentSchema=z.object({name:text.max(120),sortOrder:z.number().int().default(0),active:bool.default(true)});
adminApi.post('/companies/:companyId/departments',async(req,res,next)=>{try{const companyId=id.parse(req.params.companyId),v=parse(departmentSchema,req.body),{rows}=await pool.query('INSERT INTO departments(company_id,name,sort_order,active) VALUES($1,$2,$3,$4) RETURNING *',[companyId,v.name,v.sortOrder,v.active]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.put('/departments/:id',async(req,res,next)=>{try{const rowId=id.parse(req.params.id),v=parse(departmentSchema,req.body),{rows}=await pool.query('UPDATE departments SET name=$2,sort_order=$3,active=$4 WHERE id=$1 RETURNING *',[rowId,v.name,v.sortOrder,v.active]);res.json(rows[0])}catch(e){validation(e,res,next)}});

const positionSchema=z.object({name:text.max(120),departmentId:id.nullable().optional(),sortOrder:z.number().int().default(0),active:bool.default(true)});
adminApi.post('/companies/:companyId/positions',async(req,res,next)=>{try{const companyId=id.parse(req.params.companyId),v=parse(positionSchema,req.body);if(v.departmentId){const ok=await pool.query('SELECT 1 FROM departments WHERE id=$1 AND company_id=$2',[v.departmentId,companyId]);if(!ok.rowCount)return res.status(400).json({error:'O setor não pertence à empresa.'})}const {rows}=await pool.query('INSERT INTO positions(company_id,name,department_id,sort_order,active) VALUES($1,$2,$3,$4,$5) RETURNING *',[companyId,v.name,v.departmentId??null,v.sortOrder,v.active]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.put('/positions/:id',async(req,res,next)=>{try{const rowId=id.parse(req.params.id),v=parse(positionSchema,req.body),{rows}=await pool.query('UPDATE positions SET name=$2,department_id=$3,sort_order=$4,active=$5 WHERE id=$1 RETURNING *',[rowId,v.name,v.departmentId??null,v.sortOrder,v.active]);res.json(rows[0])}catch(e){validation(e,res,next)}});

const personSchema=z.object({name:text.max(180),role:z.enum(['leader','director']),positionId:id.nullable().optional(),departmentIds:z.array(id).default([]),active:bool.default(true)});
adminApi.post('/diagnostics/:diagnosticId/people',async(req,res,next)=>{const client=await pool.connect();try{const diagnosticId=id.parse(req.params.diagnosticId),v=parse(personSchema,req.body);await client.query('BEGIN');const diag=await client.query('SELECT company_id FROM diagnostics WHERE id=$1',[diagnosticId]);if(!diag.rows[0]){await client.query('ROLLBACK');return res.status(404).json({error:'Diagnóstico não encontrado.'})}if(v.positionId){const ok=await client.query('SELECT 1 FROM positions WHERE id=$1 AND company_id=$2',[v.positionId,diag.rows[0].company_id]);if(!ok.rowCount){await client.query('ROLLBACK');return res.status(400).json({error:'O cargo não pertence à empresa.'})}}const {rows}=await client.query('INSERT INTO people(company_id,name,role,position_id,active) VALUES($1,$2,$3,$4,$5) RETURNING *',[diag.rows[0].company_id,v.name,v.role,v.positionId??null,v.active]);for(const departmentId of v.departmentIds)await client.query(`INSERT INTO people_departments(person_id,department_id) SELECT $1,d.id FROM departments d WHERE d.id=$2 AND d.company_id=$3`,[rows[0].id,departmentId,diag.rows[0].company_id]);await client.query('INSERT INTO diagnostic_people(diagnostic_id,person_id) VALUES($1,$2)',[diagnosticId,rows[0].id]);await client.query('COMMIT');res.status(201).json(rows[0])}catch(e){await client.query('ROLLBACK');validation(e,res,next)}finally{client.release()}});
adminApi.put('/people/:id',async(req,res,next)=>{const client=await pool.connect();try{const rowId=id.parse(req.params.id),v=parse(personSchema,req.body);await client.query('BEGIN');const {rows}=await client.query('UPDATE people SET name=$2,role=$3,position_id=$4,active=$5 WHERE id=$1 RETURNING *',[rowId,v.name,v.role,v.positionId??null,v.active]);await client.query('DELETE FROM people_departments WHERE person_id=$1',[rowId]);for(const departmentId of v.departmentIds)await client.query('INSERT INTO people_departments(person_id,department_id) VALUES($1,$2)',[rowId,departmentId]);await client.query('COMMIT');res.json(rows[0])}catch(e){await client.query('ROLLBACK');validation(e,res,next)}finally{client.release()}});

const categorySchema=z.object({name:text.max(150),description:optionalText,sortOrder:z.number().int().default(0),active:bool.default(true)});
adminApi.post('/diagnostics/:diagnosticId/categories',async(req,res,next)=>{try{const diagnosticId=id.parse(req.params.diagnosticId),v=parse(categorySchema,req.body),{rows}=await pool.query('INSERT INTO categories(diagnostic_id,name,description,sort_order,active) VALUES($1,$2,$3,$4,$5) RETURNING *',[diagnosticId,v.name,v.description??null,v.sortOrder,v.active]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.put('/categories/:id',async(req,res,next)=>{try{const rowId=id.parse(req.params.id),v=parse(categorySchema,req.body),{rows}=await pool.query('UPDATE categories SET name=$2,description=$3,sort_order=$4,active=$5,updated_at=now() WHERE id=$1 RETURNING *',[rowId,v.name,v.description??null,v.sortOrder,v.active]);res.json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.get('/categories/:id/questions',async(req,res,next)=>{try{const categoryId=id.parse(req.params.id),{rows}=await pool.query(`SELECT q.*,coalesce(json_agg(json_build_object('id',ao.id,'label',ao.label,'weight',ao.weight,'favorable',ao.favorable,'sort_order',ao.sort_order,'active',ao.active) ORDER BY ao.sort_order) FILTER(WHERE ao.id IS NOT NULL),'[]') options FROM questions q LEFT JOIN answer_options ao ON ao.question_id=q.id WHERE q.category_id=$1 GROUP BY q.id ORDER BY q.sort_order,q.code`,[categoryId]);res.json(rows)}catch(e){validation(e,res,next)}});
const optionSchema=z.object({id:id.optional(),label:text.max(120),weight:z.number(),favorable:bool,sortOrder:z.number().int(),active:bool.default(true)});
const questionSchema=z.object({categoryId:id,code:text.max(30),text:text.max(1000),type:z.enum(['yes_no','satisfaction_scale','open_text']),helpText:optionalText,targetRole:z.enum(['leader','director']).nullable().optional(),required:bool.default(true),justificationRequired:bool.default(true),sortOrder:z.number().int().default(0),active:bool.default(true),options:z.array(optionSchema).default([])}).superRefine((v,ctx)=>{if(v.type==='open_text'&&v.options.length)ctx.addIssue({code:'custom',message:'Pergunta aberta não possui opções.',path:['options']});if(v.type!=='open_text'&&v.options.length<2)ctx.addIssue({code:'custom',message:'Cadastre ao menos duas opções.',path:['options']})});
async function saveQuestion(raw:unknown,questionId?:string){const v=parse(questionSchema,raw),client=await pool.connect();try{await client.query('BEGIN');const category=await client.query('SELECT diagnostic_id FROM categories WHERE id=$1',[v.categoryId]);if(!category.rows[0])throw new Error('CATEGORY_NOT_FOUND');const params=[v.categoryId,v.code,v.text,v.type,v.helpText??null,v.targetRole??null,v.type==='open_text'?false:v.justificationRequired,v.required,v.sortOrder,v.active];let q;if(questionId)q=await client.query(`UPDATE questions SET category_id=$2,code=$3,text=$4,type=$5,help_text=$6,target_role=$7,justification_required=$8,required=$9,sort_order=$10,active=$11,updated_at=now() WHERE id=$1 RETURNING *`,[questionId,...params]);else q=await client.query(`INSERT INTO questions(category_id,code,text,type,help_text,target_role,justification_required,required,sort_order,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,params);if(!q.rows[0])throw new Error('QUESTION_NOT_FOUND');await client.query('DELETE FROM answer_options WHERE question_id=$1',[q.rows[0].id]);for(const o of v.options)await client.query('INSERT INTO answer_options(question_id,label,weight,favorable,sort_order,active) VALUES($1,$2,$3,$4,$5,$6)',[q.rows[0].id,o.label,o.weight,o.favorable,o.sortOrder,o.active]);await client.query('COMMIT');return q.rows[0]}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
adminApi.post('/questions',async(req,res,next)=>{try{res.status(201).json(await saveQuestion(req.body))}catch(e){validation(e,res,next)}});
adminApi.put('/questions/:id',async(req,res,next)=>{try{res.json(await saveQuestion(req.body,id.parse(req.params.id)))}catch(e){validation(e,res,next)}});

const lcodCategorySchema=z.object({name:text.max(150),sortOrder:z.number().int().default(0),active:bool.default(true)});
adminApi.post('/diagnostics/:diagnosticId/lcod-categories',async(req,res,next)=>{try{const diagnosticId=id.parse(req.params.diagnosticId),v=parse(lcodCategorySchema,req.body),{rows}=await pool.query('INSERT INTO lcod_categories(diagnostic_id,name,sort_order,active) VALUES($1,$2,$3,$4) RETURNING *',[diagnosticId,v.name,v.sortOrder,v.active]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.put('/lcod-categories/:id',async(req,res,next)=>{try{const rowId=id.parse(req.params.id),v=parse(lcodCategorySchema,req.body),{rows}=await pool.query('UPDATE lcod_categories SET name=$2,sort_order=$3,active=$4 WHERE id=$1 RETURNING *',[rowId,v.name,v.sortOrder,v.active]);res.json(rows[0])}catch(e){validation(e,res,next)}});
const topicSchema=z.object({name:text.max(150),description:optionalText,sortOrder:z.number().int().default(0),active:bool.default(true)});
adminApi.post('/lcod-categories/:categoryId/topics',async(req,res,next)=>{try{const categoryId=id.parse(req.params.categoryId),v=parse(topicSchema,req.body),{rows}=await pool.query('INSERT INTO lcod_topics(lcod_category_id,name,description,sort_order,active) VALUES($1,$2,$3,$4,$5) RETURNING *',[categoryId,v.name,v.description??null,v.sortOrder,v.active]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
adminApi.put('/lcod-topics/:id',async(req,res,next)=>{try{const rowId=id.parse(req.params.id),v=parse(topicSchema,req.body),{rows}=await pool.query('UPDATE lcod_topics SET name=$2,description=$3,sort_order=$4,active=$5 WHERE id=$1 RETURNING *',[rowId,v.name,v.description??null,v.sortOrder,v.active]);res.json(rows[0])}catch(e){validation(e,res,next)}});

adminApi.get('/diagnostics/:id/interviews',async(req,res,next)=>{try{const diagnosticId=id.parse(req.params.id),status=z.enum(['not_started','in_progress','completed','cancelled']).optional().parse(req.query.status);const {rows}=await pool.query(`SELECT i.id,i.anonymous_code,i.status,i.started_at,i.completed_at,i.updated_at,ip.gender,ip.tenure_band,d.name department_name,p.name position_name,count(a.id)::int answered_count,(SELECT count(*)::int FROM questions q JOIN categories c ON c.id=q.category_id WHERE c.diagnostic_id=i.diagnostic_id AND q.active AND c.active) total_questions FROM interviews i LEFT JOIN interview_profiles ip ON ip.interview_id=i.id LEFT JOIN departments d ON d.id=ip.department_id LEFT JOIN positions p ON p.id=ip.position_id LEFT JOIN answers a ON a.interview_id=i.id WHERE i.diagnostic_id=$1 AND ($2::interview_status IS NULL OR i.status=$2) GROUP BY i.id,ip.interview_id,d.name,p.name ORDER BY i.updated_at DESC`,[diagnosticId,status??null]);res.json(rows)}catch(e){validation(e,res,next)}});
adminApi.post('/diagnostics/:id/interviews',async(req,res,next)=>{try{const diagnosticId=id.parse(req.params.id);const {rows}=await pool.query(`INSERT INTO interviews(diagnostic_id,anonymous_code) SELECT $1,'ENT-'||lpad((count(*)+1)::text,4,'0') FROM interviews WHERE diagnostic_id=$1 RETURNING *`,[diagnosticId]);res.status(201).json(rows[0])}catch(e){validation(e,res,next)}});
const profileSchema=z.object({gender:optionalText,tenureBand:optionalText,departmentId:id.nullable().optional(),positionId:id.nullable().optional(),registeredRoleDivergence:bool.nullable().optional(),personIds:z.array(id).max(4).default([])});
adminApi.put('/interviews/:id/profile',async(req,res,next)=>{const client=await pool.connect();try{const interviewId=id.parse(req.params.id),v=parse(profileSchema,req.body);await client.query('BEGIN');const interview=await client.query('SELECT i.diagnostic_id,d.company_id FROM interviews i JOIN diagnostics d ON d.id=i.diagnostic_id WHERE i.id=$1',[interviewId]);if(!interview.rows[0]){await client.query('ROLLBACK');return res.status(404).json({error:'Entrevista não encontrada.'})}if(v.departmentId){const ok=await client.query('SELECT 1 FROM departments WHERE id=$1 AND company_id=$2',[v.departmentId,interview.rows[0].company_id]);if(!ok.rowCount){await client.query('ROLLBACK');return res.status(400).json({error:'Setor inválido para este diagnóstico.'})}}if(v.positionId){const ok=await client.query('SELECT 1 FROM positions WHERE id=$1 AND company_id=$2',[v.positionId,interview.rows[0].company_id]);if(!ok.rowCount){await client.query('ROLLBACK');return res.status(400).json({error:'Cargo inválido para este diagnóstico.'})}}await client.query(`INSERT INTO interview_profiles(interview_id,gender,tenure_band,department_id,position_id,registered_role_divergence) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(interview_id) DO UPDATE SET gender=excluded.gender,tenure_band=excluded.tenure_band,department_id=excluded.department_id,position_id=excluded.position_id,registered_role_divergence=excluded.registered_role_divergence,updated_at=now()`,[interviewId,v.gender??null,v.tenureBand??null,v.departmentId??null,v.positionId??null,v.registeredRoleDivergence??null]);await client.query('DELETE FROM interview_people WHERE interview_id=$1',[interviewId]);for(let i=0;i<v.personIds.length;i++){const allowed=await client.query('SELECT 1 FROM diagnostic_people WHERE diagnostic_id=$1 AND person_id=$2 AND active',[interview.rows[0].diagnostic_id,v.personIds[i]]);if(!allowed.rowCount){await client.query('ROLLBACK');return res.status(400).json({error:'Liderança ou diretoria não pertence ao diagnóstico.'})}await client.query('INSERT INTO interview_people(interview_id,person_id,relationship_order) VALUES($1,$2,$3)',[interviewId,v.personIds[i],i+1])}await client.query('COMMIT');res.json({saved:true})}catch(e){await client.query('ROLLBACK');validation(e,res,next)}finally{client.release()}});
