import { Router } from 'express';
import { z } from 'zod';
import PDFDocument from 'pdfkit';
import { pool } from './db/pool.js';

export const reportApi=Router();
const uuid=z.string().uuid();
const requestSchema=z.object({type:z.enum(['general','leadership']),personId:uuid.optional(),includeComments:z.boolean().default(true)}).refine(x=>x.type==='general'||x.personId,{message:'Selecione a liderança.',path:['personId']});
const colors={dark:'173F39',green:'176D5C',mint:'E7F2EF',gold:'EFB149',red:'B64C44',cream:'F7F8F7',gray:'687773',line:'DFE6E4',white:'FFFFFF'};

type ReportData={diagnostic:any;summary:any;categories:any[];topics:any[];comments:any[];plans:any[];person?:any;questions?:any[];privacy:string};
const safeName=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase();
const cleanText=(value:string)=>value.replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim();
const redactComment=(value:string)=>cleanText(value).replace(/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi,'[e-mail removido]').replace(/(?:https?:\/\/|www\.)\S+/gi,'[link removido]').replace(/\b\d{3}\.?\d{3}\.?\d{3}-?\d{2}\b/g,'[documento removido]').replace(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?\d{4,5}[-\s]?\d{4}/g,'[telefone removido]');
const sanitize=(value:any):any=>value instanceof Date?value:Array.isArray(value)?value.map(sanitize):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,sanitize(v)])):typeof value==='string'?cleanText(value):value;
const pct=(value:any)=>value==null?'—':`${Number(value).toFixed(1).replace('.0','')}%`;
const score=(value:any)=>value==null?'—':Number(value).toFixed(2).replace('.',',');
const date=(value:any)=>{if(!value)return'Não definido';const raw=String(value),parsed=/^\d{4}-\d{2}-\d{2}/.test(raw)?new Date(`${raw.slice(0,10)}T12:00:00-03:00`):new Date(value);return new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo'}).format(parsed)};

async function loadReport(diagnosticId:string,type:'general'|'leadership',personId?:string,includeComments=true):Promise<ReportData>{
 const diagnostic=(await pool.query(`SELECT d.*,c.name company_name,c.trade_name FROM diagnostics d JOIN companies c ON c.id=d.company_id WHERE d.id=$1`,[diagnosticId])).rows[0];
 if(!diagnostic)throw Object.assign(new Error('Diagnóstico não encontrado.'),{status:404});
 const categories=(await pool.query(`SELECT c.id,c.name,count(a.id)::int responses,round(avg(ao.weight),2)::float average,round(100.0*count(*) FILTER(WHERE ao.favorable)/nullif(count(ao.id),0),1)::float favorability FROM categories c LEFT JOIN questions q ON q.category_id=c.id AND q.active LEFT JOIN answers a ON a.question_id=q.id AND a.interview_id IN(SELECT id FROM interviews WHERE diagnostic_id=$1 AND status='completed') LEFT JOIN answer_options ao ON ao.id=a.answer_option_id WHERE c.diagnostic_id=$1 AND c.active GROUP BY c.id ORDER BY c.sort_order`,[diagnosticId])).rows;
 const generalTopics=(await pool.query(`SELECT lt.id,lt.name,count(DISTINCT cc.comment_id)::int mentions,count(DISTINCT cc.comment_id) FILTER(WHERE cc.sentiment='positive')::int positive,count(DISTINCT cc.comment_id) FILTER(WHERE cc.sentiment='negative')::int negative FROM lcod_topics lt JOIN lcod_categories lc ON lc.id=lt.lcod_category_id LEFT JOIN comment_classifications cc ON cc.lcod_topic_id=lt.id AND cc.review_status IN('approved','edited') WHERE lc.diagnostic_id=$1 AND lt.active GROUP BY lt.id HAVING count(DISTINCT cc.comment_id)>0 ORDER BY mentions DESC LIMIT 12`,[diagnosticId])).rows;
 const plans=(await pool.query(`SELECT problem,proposed_action,priority,responsible,due_date,status FROM action_plans WHERE diagnostic_id=$1 AND status<>'cancelled' ORDER BY CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,due_date NULLS LAST LIMIT 12`,[diagnosticId])).rows;
 if(type==='general'){
  const summary=(await pool.query(`SELECT count(DISTINCT i.id)::int completed_interviews,count(a.id)::int response_count,round(avg(ao.weight),2)::float average,round(100.0*count(*) FILTER(WHERE ao.favorable)/nullif(count(ao.id),0),1)::float favorability FROM interviews i LEFT JOIN answers a ON a.interview_id=i.id LEFT JOIN answer_options ao ON ao.id=a.answer_option_id WHERE i.diagnostic_id=$1 AND i.status='completed'`,[diagnosticId])).rows[0];
  const comments=includeComments&&summary.completed_interviews>=diagnostic.minimum_sample_size?(await pool.query(`SELECT DISTINCT ON(cm.id) cm.id,cm.original_text,cm.normalized_text,q.code,c.name category FROM comments cm JOIN answers a ON a.id=cm.answer_id JOIN interviews i ON i.id=a.interview_id JOIN questions q ON q.id=a.question_id JOIN categories c ON c.id=q.category_id WHERE i.diagnostic_id=$1 AND i.status='completed' ORDER BY cm.id,cm.created_at DESC LIMIT 10`,[diagnosticId])).rows.map(c=>({...c,original_text:redactComment(c.normalized_text||c.original_text),normalized_text:undefined})):[];
  return{diagnostic,summary,categories,topics:generalTopics,comments,plans,privacy:`Resultados agregados. Recortes com menos de ${diagnostic.minimum_sample_size} participantes não são exibidos.`};
 }
 const person=(await pool.query(`SELECT p.id,p.name,p.role,count(DISTINCT a.interview_id) FILTER(WHERE i.id IS NOT NULL)::int evaluation_count FROM people p JOIN diagnostic_people dp ON dp.person_id=p.id AND dp.diagnostic_id=$1 LEFT JOIN answers a ON a.related_person_id=p.id LEFT JOIN interviews i ON i.id=a.interview_id AND i.status='completed' WHERE p.id=$2 GROUP BY p.id`,[diagnosticId,personId])).rows[0];
 if(!person)throw Object.assign(new Error('Liderança não encontrada neste diagnóstico.'),{status:404});
 if(person.evaluation_count<diagnostic.minimum_sample_size)throw Object.assign(new Error(`Relatório bloqueado: são necessárias pelo menos ${diagnostic.minimum_sample_size} avaliações para preservar o anonimato.`),{status:403});
 const summary=(await pool.query(`SELECT count(a.id)::int response_count,round(avg(ao.weight),2)::float average,round(100.0*count(*) FILTER(WHERE ao.favorable)/nullif(count(ao.id),0),1)::float favorability FROM answers a JOIN interviews i ON i.id=a.interview_id AND i.status='completed' LEFT JOIN answer_options ao ON ao.id=a.answer_option_id WHERE i.diagnostic_id=$1 AND a.related_person_id=$2`,[diagnosticId,personId])).rows[0];
 const questions=(await pool.query(`SELECT q.code,q.text,count(a.id)::int responses,round(avg(ao.weight),2)::float average,round(100.0*count(*) FILTER(WHERE ao.favorable)/nullif(count(ao.id),0),1)::float favorability FROM questions q JOIN categories c ON c.id=q.category_id LEFT JOIN answers a ON a.question_id=q.id AND a.related_person_id=$2 AND a.interview_id IN(SELECT id FROM interviews WHERE diagnostic_id=$1 AND status='completed') LEFT JOIN answer_options ao ON ao.id=a.answer_option_id WHERE c.diagnostic_id=$1 AND q.target_role=$3 AND q.active GROUP BY q.id ORDER BY q.sort_order`,[diagnosticId,personId,person.role])).rows;
 const topics=(await pool.query(`SELECT lt.id,lt.name,count(DISTINCT cc.comment_id)::int mentions,count(DISTINCT cc.comment_id) FILTER(WHERE cc.sentiment='positive')::int positive,count(DISTINCT cc.comment_id) FILTER(WHERE cc.sentiment='negative')::int negative FROM lcod_topics lt JOIN lcod_categories lc ON lc.id=lt.lcod_category_id JOIN comment_classifications cc ON cc.lcod_topic_id=lt.id AND cc.review_status IN('approved','edited') JOIN comments cm ON cm.id=cc.comment_id JOIN answers a ON a.id=cm.answer_id JOIN interviews i ON i.id=a.interview_id AND i.status='completed' WHERE lc.diagnostic_id=$1 AND lt.active AND a.related_person_id=$2 GROUP BY lt.id HAVING count(DISTINCT cc.comment_id)>0 ORDER BY mentions DESC LIMIT 12`,[diagnosticId,personId])).rows;
 const comments=includeComments?(await pool.query(`SELECT DISTINCT ON(cm.id) cm.id,cm.original_text,cm.normalized_text,q.code,c.name category FROM comments cm JOIN answers a ON a.id=cm.answer_id JOIN interviews i ON i.id=a.interview_id JOIN questions q ON q.id=a.question_id JOIN categories c ON c.id=q.category_id WHERE i.diagnostic_id=$1 AND i.status='completed' AND a.related_person_id=$2 ORDER BY cm.id,cm.created_at DESC LIMIT 12`,[diagnosticId,personId])).rows.map(c=>({...c,original_text:redactComment(c.normalized_text||c.original_text),normalized_text:undefined})):[];
 return{diagnostic,summary:{...summary,completed_interviews:person.evaluation_count},categories:[],topics,comments,plans:[],person,questions,privacy:`Relatório confidencial. Dados liberados somente porque há ${person.evaluation_count} avaliações válidas, acima da amostra mínima de ${diagnostic.minimum_sample_size}.`};
}

reportApi.get('/diagnostics/:id/reports/options',async(req,res,next)=>{try{const diagnosticId=uuid.parse(req.params.id),diagnostic=(await pool.query('SELECT minimum_sample_size FROM diagnostics WHERE id=$1',[diagnosticId])).rows[0];if(!diagnostic)return res.status(404).json({error:'Diagnóstico não encontrado.'});const {rows}=await pool.query(`SELECT p.id,p.name,p.role,count(DISTINCT a.interview_id) FILTER(WHERE i.id IS NOT NULL)::int evaluation_count FROM people p JOIN diagnostic_people dp ON dp.person_id=p.id AND dp.diagnostic_id=$1 LEFT JOIN answers a ON a.related_person_id=p.id LEFT JOIN interviews i ON i.id=a.interview_id AND i.status='completed' WHERE p.role IN('leader','director') GROUP BY p.id ORDER BY p.role,p.name`,[diagnosticId]);res.json({minimumSampleSize:diagnostic.minimum_sample_size,people:rows.map(x=>({...x,available:x.evaluation_count>=diagnostic.minimum_sample_size}))})}catch(e){next(e)}});

reportApi.post('/diagnostics/:id/reports/export',async(req,res,next)=>{try{const diagnosticId=uuid.parse(req.params.id),format=z.enum(['pdf','pptx']).parse(req.query.format),input=requestSchema.parse(req.body),data=sanitize(await loadReport(diagnosticId,input.type,input.personId,input.includeComments)) as ReportData;const base=`relatorio-${input.type==='general'?'geral':safeName(data.person.name)}-${safeName(data.diagnostic.name)}`,buffer=format==='pdf'?await createPdf(data,input.type):await createPptx(data,input.type);res.setHeader('Content-Type',format==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.presentationml.presentation');res.setHeader('Content-Disposition',`attachment; filename="${base}.${format}"`);res.send(buffer)}catch(e:any){if(e instanceof z.ZodError)return res.status(400).json({error:'Verifique as opções do relatório.',fields:e.flatten().fieldErrors});if(e?.status)return res.status(e.status).json({error:e.message});next(e)}});

export function createPdf(data:ReportData,type:'general'|'leadership'){return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:42,bufferPages:true,info:{Title:`Relatório ${type==='general'?'geral':data.person.name}`,Author:data.diagnostic.company_name}}),chunks:Buffer[]=[];doc.on('data',x=>chunks.push(x));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);const pageTitle=(title:string,sub?:string)=>{doc.fillColor(`#${colors.dark}`).font('Helvetica-Bold').fontSize(20).text(title);if(sub)doc.fillColor(`#${colors.gray}`).font('Helvetica').fontSize(9).text(sub,{lineGap:2});doc.moveDown(1)};const newPage=(title:string,sub?:string)=>{doc.addPage();pageTitle(title,sub)};const metric=(x:number,y:number,w:number,label:string,value:string)=>{doc.roundedRect(x,y,w,58,7).fillAndStroke(`#${colors.cream}`,`#${colors.line}`);doc.fillColor(`#${colors.gray}`).font('Helvetica').fontSize(7).text(label.toUpperCase(),x+10,y+10,{width:w-20});doc.fillColor(`#${colors.dark}`).font('Helvetica-Bold').fontSize(17).text(value,x+10,y+27,{width:w-20})};
 doc.rect(0,0,595,842).fill(`#${colors.dark}`);doc.fillColor(`#${colors.gold}`).font('Helvetica-Bold').fontSize(11).text('DIAGNÓSTICO ORGANIZACIONAL',48,70);doc.fillColor(`#${colors.white}`).fontSize(29).text(type==='general'?'Relatório geral':'Relatório confidencial de liderança',48,112,{width:490});doc.font('Helvetica').fontSize(15).fillColor('#D6E3E0').text(type==='general'?(data.diagnostic.trade_name||data.diagnostic.company_name):data.person.name,48,205,{width:490});doc.fontSize(10).text(`${data.diagnostic.name}  |  ${date(data.diagnostic.starts_on)} a ${date(data.diagnostic.ends_on)}`,48,245,{width:490});doc.roundedRect(48,650,499,85,8).fill('#214F48');doc.fillColor(`#${colors.white}`).font('Helvetica-Bold').fontSize(9).text('PRIVACIDADE E USO',62,667);doc.fillColor('#D6E3E0').font('Helvetica').fontSize(8).text(data.privacy,62,686,{width:465,lineGap:3});doc.fontSize(8).text(`Gerado em ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'long',timeZone:'America/Sao_Paulo'}).format(new Date())}`,48,760);
 newPage('Resumo executivo',type==='leadership'?`Visão individual protegida de ${data.person.name}`:'Visão consolidada do diagnóstico');metric(42,105,118,'Participantes',String(data.summary.completed_interviews??0));metric(170,105,118,'Respostas',String(data.summary.response_count??0));metric(298,105,118,'Favorabilidade',pct(data.summary.favorability));metric(426,105,127,'Média ponderada',score(data.summary.average));doc.fillColor(`#${colors.dark}`).font('Helvetica-Bold').fontSize(12).text(type==='general'?'Resultados por categoria':'Resultados por pergunta',42,190);
 const rows=(type==='general'?data.categories:data.questions||[]).slice(0,12);let y=220;for(const row of rows){const label=type==='general'?row.name:`${row.code} - ${row.text}`;doc.fillColor(`#${colors.dark}`).font('Helvetica').fontSize(8).text(label,42,y,{width:265,ellipsis:true});doc.roundedRect(315,y,180,8,4).fill('#E7ECEB');doc.roundedRect(315,y,Math.max(2,180*Number(row.favorability||0)/100),8,4).fill(`#${Number(row.favorability)>=75?colors.green:Number(row.favorability)<60?colors.red:colors.gold}`);doc.fillColor(`#${colors.dark}`).font('Helvetica-Bold').text(pct(row.favorability),505,y-1,{width:45,align:'right'});y+=37}
 if(data.topics.length){newPage('Agrupadores de comentários');doc.fillColor(`#${colors.gray}`).font('Helvetica').fontSize(9).text('Temas recorrentes classificados sem identificação dos participantes.',42,90);y=125;data.topics.forEach((t,i)=>{doc.fillColor(`#${colors.dark}`).font('Helvetica-Bold').fontSize(10).text(`${i+1}. ${t.name}`,42,y,{width:260});doc.font('Helvetica').fontSize(8).fillColor(`#${colors.gray}`).text(`${t.mentions} comentários  |  ${t.positive} positivos  |  ${t.negative} negativos`,315,y,{width:235,align:'right'});doc.moveTo(42,y+22).lineTo(553,y+22).strokeColor(`#${colors.line}`).stroke();y+=42})}
 if(data.comments.length){newPage('Comentários selecionados');doc.fillColor(`#${colors.gray}`).font('Helvetica').fontSize(8).text('Comentários apresentados sem nomes, códigos de entrevista ou dados de perfil.',42,88);y=120;for(const c of data.comments){const h=doc.heightOfString(c.original_text,{width:465,lineGap:2})+35;if(y+h>780){newPage('Comentários selecionados (continuação)');y=95}doc.roundedRect(42,y,511,h,6).fillAndStroke(`#${colors.cream}`,`#${colors.line}`);doc.fillColor(`#${colors.green}`).font('Helvetica-Bold').fontSize(7).text(`${c.code} · ${c.category}`.toUpperCase(),54,y+10);doc.fillColor(`#${colors.dark}`).font('Helvetica').fontSize(9).text(c.original_text,54,y+25,{width:475,lineGap:2});y+=h+10}}
 if(type==='general'&&data.plans.length){newPage('Plano de ação');y=100;for(const p of data.plans){const h=70;doc.roundedRect(42,y,511,h,6).fillAndStroke(`#${colors.cream}`,`#${colors.line}`);doc.fillColor(`#${colors.dark}`).font('Helvetica-Bold').fontSize(9).text(p.problem,54,y+10,{width:475});doc.fillColor(`#${colors.gray}`).font('Helvetica').fontSize(8).text(p.proposed_action,54,y+27,{width:475,height:25,ellipsis:true});doc.fontSize(7).text(`Responsável: ${p.responsible}  |  Prazo: ${date(p.due_date)}  |  Status: ${p.status}`,54,y+55,{width:475});y+=80;if(y>750){newPage('Plano de ação (continuação)');y=100}}}
 const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.fillColor('#899491').font('Helvetica').fontSize(7).text(`${data.diagnostic.name} · Documento ${type==='leadership'?'confidencial':'agregado'}`,42,790,{width:430,lineBreak:false});doc.text(`${i+1}/${range.count}`,500,790,{width:53,align:'right',lineBreak:false})}doc.end()})}

export async function createPptx(data:ReportData,type:'general'|'leadership'){const PptxGenJS:any=(await import('pptxgenjs')).default;const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author=data.diagnostic.company_name;pptx.subject='Relatório de diagnóstico organizacional';pptx.title=type==='general'?'Relatório geral':`Relatório de ${data.person.name}`;pptx.company=data.diagnostic.company_name;pptx.lang='pt-BR';pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'pt-BR'};const footer=(slide:any,n:number)=>{slide.addText(`${data.diagnostic.name} · ${type==='leadership'?'Confidencial':'Resultados agregados'}`,{x:.55,y:7.15,w:10.8,h:.18,fontSize:8,color:'899491'});slide.addText(String(n),{x:12,y:7.15,w:.7,h:.18,fontSize:8,color:'899491',align:'right'})};let n=1;let slide=pptx.addSlide();slide.background={color:colors.dark};slide.addText('DIAGNÓSTICO ORGANIZACIONAL',{x:.7,y:.7,w:6,h:.3,fontSize:12,bold:true,color:colors.gold,charSpacing:1.5});slide.addText(type==='general'?'Relatório geral':'Relatório confidencial de liderança',{x:.7,y:1.35,w:11.5,h:1.05,fontSize:30,bold:true,color:colors.white,breakLine:false,fit:'shrink'});slide.addText(type==='general'?(data.diagnostic.trade_name||data.diagnostic.company_name):data.person.name,{x:.7,y:2.65,w:10.5,h:.5,fontSize:20,color:'D6E3E0'});slide.addText(`${data.diagnostic.name}  |  ${date(data.diagnostic.starts_on)} a ${date(data.diagnostic.ends_on)}`,{x:.7,y:3.35,w:10.5,h:.35,fontSize:12,color:'D6E3E0'});slide.addShape(pptx.ShapeType.roundRect,{x:.7,y:5.55,w:11.9,h:.9,rectRadius:.05,fill:{color:'214F48'},line:{color:'214F48'}});slide.addText('PRIVACIDADE E USO',{x:.95,y:5.75,w:2.1,h:.2,fontSize:10,bold:true,color:colors.white});slide.addText(data.privacy,{x:3,y:5.68,w:9.2,h:.35,fontSize:10,color:'D6E3E0',fit:'shrink'});footer(slide,n++);
 slide=pptx.addSlide();slide.background={color:colors.white};slide.addText('Resumo executivo',{x:.6,y:.4,w:7,h:.5,fontSize:26,bold:true,color:colors.dark});const metrics=[['Participantes',data.summary.completed_interviews],['Respostas',data.summary.response_count],['Favorabilidade',pct(data.summary.favorability)],['Média ponderada',score(data.summary.average)]];metrics.forEach((m,i)=>{slide.addShape(pptx.ShapeType.roundRect,{x:.6+i*3.1,y:1.25,w:2.75,h:1,fill:{color:colors.cream},line:{color:colors.line},radius:.06});slide.addText(String(m[0]).toUpperCase(),{x:.82+i*3.1,y:1.48,w:2.3,h:.18,fontSize:9,color:colors.gray,bold:true});slide.addText(String(m[1]??0),{x:.82+i*3.1,y:1.75,w:2.3,h:.35,fontSize:22,color:colors.dark,bold:true})});slide.addText(type==='general'?'Resultados por categoria':'Resultados por pergunta',{x:.6,y:2.65,w:6,h:.35,fontSize:18,bold:true,color:colors.dark});const rows=(type==='general'?data.categories:data.questions||[]).slice(0,8);rows.forEach((r,i)=>{const yy=3.2+i*.43,label=type==='general'?r.name:`${r.code} · ${r.text}`;slide.addText(label,{x:.65,y:yy,w:5.4,h:.22,fontSize:10,color:colors.dark,fit:'shrink'});slide.addShape(pptx.ShapeType.roundRect,{x:6.25,y:yy+.03,w:5.15,h:.12,fill:{color:'E7ECEB'},line:{color:'E7ECEB'},radius:.04});slide.addShape(pptx.ShapeType.roundRect,{x:6.25,y:yy+.03,w:Math.max(.05,5.15*Number(r.favorability||0)/100),h:.12,fill:{color:Number(r.favorability)>=75?colors.green:Number(r.favorability)<60?colors.red:colors.gold},line:{color:Number(r.favorability)>=75?colors.green:Number(r.favorability)<60?colors.red:colors.gold},radius:.04});slide.addText(pct(r.favorability),{x:11.55,y:yy-.03,w:.8,h:.2,fontSize:10,bold:true,color:colors.dark,align:'right'})});footer(slide,n++);
 if(data.topics.length){slide=pptx.addSlide();slide.addText('Agrupadores de comentários',{x:.6,y:.4,w:8,h:.5,fontSize:26,bold:true,color:colors.dark});slide.addText('Temas recorrentes sem identificação dos participantes',{x:.6,y:.95,w:8,h:.3,fontSize:12,color:colors.gray});data.topics.slice(0,10).forEach((t,i)=>{const yy=1.5+i*.5;slide.addText(String(i+1).padStart(2,'0'),{x:.65,y:yy,w:.4,h:.23,fontSize:10,bold:true,color:colors.green});slide.addText(t.name,{x:1.15,y:yy,w:5.5,h:.23,fontSize:12,bold:true,color:colors.dark});slide.addText(`${t.mentions} menções`,{x:7,y:yy,w:1.2,h:.23,fontSize:10,color:colors.gray});slide.addText(`${t.positive} positivas`,{x:8.4,y:yy,w:1.3,h:.23,fontSize:10,color:colors.green});slide.addText(`${t.negative} negativas`,{x:9.9,y:yy,w:1.4,h:.23,fontSize:10,color:colors.red});slide.addShape(pptx.ShapeType.line,{x:.65,y:yy+.34,w:11.5,h:0,line:{color:colors.line,width:1}})});footer(slide,n++)}
 if(data.comments.length){for(let offset=0;offset<data.comments.length;offset+=6){slide=pptx.addSlide();slide.addText(offset?'Comentários selecionados · continuação':'Comentários selecionados',{x:.6,y:.4,w:9,h:.5,fontSize:26,bold:true,color:colors.dark});slide.addText('Trechos anônimos para contextualizar os resultados',{x:.6,y:.95,w:8,h:.3,fontSize:12,color:colors.gray});data.comments.slice(offset,offset+6).forEach((c,i)=>{const yy=1.45+i*.82;slide.addShape(pptx.ShapeType.roundRect,{x:.65,y:yy,w:11.9,h:.68,fill:{color:colors.cream},line:{color:colors.line},radius:.04});slide.addText(`${c.code} · ${c.category}`.toUpperCase(),{x:.85,y:yy+.1,w:2.1,h:.15,fontSize:8,bold:true,color:colors.green});slide.addText(c.original_text,{x:2.65,y:yy+.1,w:9.45,h:.42,fontSize:11,color:colors.dark,fit:'shrink',valign:'mid'})});footer(slide,n++)}}
 if(type==='general'&&data.plans.length){slide=pptx.addSlide();slide.addText('Plano de ação',{x:.6,y:.4,w:7,h:.5,fontSize:26,bold:true,color:colors.dark});data.plans.slice(0,6).forEach((p,i)=>{const yy=1.25+i*.88;slide.addText(p.problem,{x:.7,y:yy,w:4.1,h:.28,fontSize:12,bold:true,color:colors.dark,fit:'shrink'});slide.addText(p.proposed_action,{x:4.9,y:yy,w:5.1,h:.42,fontSize:10,color:colors.gray,fit:'shrink'});slide.addText(p.responsible,{x:10.2,y:yy,w:1.3,h:.22,fontSize:9,color:colors.dark,fit:'shrink'});slide.addText(date(p.due_date),{x:11.55,y:yy,w:.8,h:.22,fontSize:9,color:colors.gray,align:'right'});slide.addShape(pptx.ShapeType.line,{x:.7,y:yy+.58,w:11.65,h:0,line:{color:colors.line,width:1}})});footer(slide,n++)}
 const out=await pptx.write({outputType:'nodebuffer'});return Buffer.isBuffer(out)?out:Buffer.from(out as ArrayBuffer)}
