import { useEffect,useMemo,useState } from 'react';
import { AlertCircle,CheckCircle2,Clock3,Edit3,Eye,Plus,Search,Target,Trash2,X } from 'lucide-react';
import { api,json } from './api';

type Status='planned'|'in_progress'|'completed'|'cancelled';
type Priority='low'|'medium'|'high';
type Plan={id:string;diagnostic_id:string;diagnostic_name:string;problem:string;proposed_action:string;priority:Priority;responsible:string;due_date:string|null;status:Status;notes?:string;created_at:string;updated_at:string;overdue:boolean};
type Form={diagnosticId:string;problem:string;proposedAction:string;priority:Priority;responsible:string;status:Status;notes:string};
const statusLabels:Record<Status,string>={planned:'Não iniciado',in_progress:'Em andamento',completed:'Concluído',cancelled:'Cancelado'};
const priorityLabels:Record<Priority,string>={low:'Baixa',medium:'Média',high:'Alta'};

export function ActionPlans({companyId,diagnosticId}:{companyId:string;diagnosticId:string}){
 const [items,setItems]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState(''),[priorityFilter,setPriorityFilter]=useState(''),[responsibleFilter,setResponsibleFilter]=useState(''),[editing,setEditing]=useState<Plan|null|undefined>(undefined),[detail,setDetail]=useState<Plan>(),[deleting,setDeleting]=useState<Plan>();
 const load=()=>{setLoading(true);api<Plan[]>(`/companies/${companyId}/action-plans`).then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[companyId]);
 const responsible=useMemo(()=>[...new Set(items.map(x=>x.responsible))].sort(),[items]);
 const filtered=items.filter(x=>(!statusFilter||x.status===statusFilter)&&(!priorityFilter||x.priority===priorityFilter)&&(!responsibleFilter||x.responsible===responsibleFilter)&&(!search.trim()||`${x.problem} ${x.proposed_action}`.toLocaleLowerCase('pt-BR').includes(search.trim().toLocaleLowerCase('pt-BR'))));
 const success=(message:string)=>{setNotice(message);setTimeout(()=>setNotice(''),3500);load()};
 const changeStatus=async(plan:Plan,value:Status)=>{try{await api(`/companies/${companyId}/action-plans/${plan.id}/status`,json('PATCH',{status:value}));success('Status atualizado com sucesso.')}catch(e){setError((e as Error).message)}};
 const remove=async()=>{if(!deleting)return;try{await api(`/companies/${companyId}/action-plans/${deleting.id}`,{method:'DELETE'});setDeleting(undefined);success('Plano de ação excluído.')}catch(e){setError((e as Error).message)}};
 return <div className="action-page"><div className="action-head"><div><h2>Plano de Ação</h2><p>Registre, acompanhe e gerencie ações de melhoria identificadas na empresa.</p></div><button className="primary" onClick={()=>setEditing(null)}><Plus/> Novo Plano de Ação</button></div>
 {error&&<div className="errorbar"><AlertCircle/>{error}<button onClick={()=>setError('')}><X/></button></div>}{notice&&<div className="successbar"><CheckCircle2/>{notice}</div>}
 <div className="action-metrics"><Metric icon={<Target/>} label="Total de ações" value={items.length}/><Metric icon={<Clock3/>} label="Em andamento" value={items.filter(x=>x.status==='in_progress').length}/><Metric icon={<AlertCircle/>} label="Atrasadas" value={items.filter(x=>x.overdue).length} tone="late"/><Metric icon={<CheckCircle2/>} label="Concluídas" value={items.filter(x=>x.status==='completed').length} tone="done"/></div>
 <div className="action-filters"><label className="action-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por problema ou ação..."/></label><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos os status</option>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="">Todas as prioridades</option><option value="high">Alta</option><option value="medium">Média</option><option value="low">Baixa</option></select>{responsible.length>1&&<select value={responsibleFilter} onChange={e=>setResponsibleFilter(e.target.value)}><option value="">Todos os responsáveis</option>{responsible.map(x=><option key={x}>{x}</option>)}</select>}</div>
 {loading?<Empty title="Carregando planos" text="Consultando os planos de ação da empresa..."/>:!filtered.length?<Empty title={items.length?'Nenhum plano encontrado':'Nenhum plano de ação cadastrado'} text={items.length?'Ajuste os filtros ou o termo pesquisado.':'Crie o primeiro plano para acompanhar uma oportunidade de melhoria.'}/>:<div className="action-list">{filtered.map(plan=><article className={`action-card priority-${plan.priority} ${plan.overdue?'overdue':''}`} key={plan.id}><div className="action-card-top"><span className={`priority-badge ${plan.priority}`}><i/>{priorityLabels[plan.priority]}</span><span className={`action-status ${plan.status}`}>{statusLabels[plan.status]}</span>{plan.overdue&&<span className="overdue-badge"><AlertCircle/> Prazo vencido</span>}</div><div className="action-flow"><section><small>PROBLEMA</small><h3>{plan.problem}</h3></section><i>→</i><section><small>AÇÃO PROPOSTA</small><p>{plan.proposed_action}</p></section></div><div className="action-meta"><span><b>Responsável</b>{plan.responsible}</span>{plan.due_date&&<span><b>Prazo</b>{date(plan.due_date)}</span>}<span><b>Diagnóstico</b>{plan.diagnostic_name}</span></div><footer><select aria-label="Alterar status" value={plan.status} onChange={e=>changeStatus(plan,e.target.value as Status)}>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><div><button title="Visualizar detalhes" onClick={()=>setDetail(plan)}><Eye/></button><button title="Editar" onClick={()=>setEditing(plan)}><Edit3/></button><button className="danger" title="Excluir" onClick={()=>setDeleting(plan)}><Trash2/></button></div></footer></article>)}</div>}
 {editing!==undefined&&<PlanModal companyId={companyId} diagnosticId={diagnosticId} plan={editing} close={()=>setEditing(undefined)} saved={()=>{setEditing(undefined);success(editing?'Plano de ação atualizado.':'Plano de ação criado.')}}/>}{detail&&<Detail plan={detail} close={()=>setDetail(undefined)}/>} {deleting&&<Confirm plan={deleting} close={()=>setDeleting(undefined)} remove={remove}/>}</div>
}

function Metric({icon,label,value,tone='' }:{icon:any;label:string;value:number;tone?:string}){return <div className={`action-metric ${tone}`}>{icon}<span>{label}</span><strong>{value}</strong></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="action-empty"><Target/><h3>{title}</h3><p>{text}</p></div>}
function PlanModal({companyId,diagnosticId,plan,close,saved}:{companyId:string;diagnosticId:string;plan:Plan|null;close:()=>void;saved:()=>void}){const [form,setForm]=useState<Form>(plan?{diagnosticId:plan.diagnostic_id,problem:plan.problem,proposedAction:plan.proposed_action,priority:plan.priority,responsible:plan.responsible,status:plan.status,notes:plan.notes||''}:{diagnosticId,problem:'',proposedAction:'',priority:'medium',responsible:'',status:'planned',notes:''}),[saving,setSaving]=useState(false),[error,setError]=useState('');const valid=form.problem.trim()&&form.proposedAction.trim()&&form.priority&&form.responsible.trim();const save=async()=>{if(!valid)return setError('Preencha todos os campos obrigatórios.');setSaving(true);setError('');try{await api(plan?`/companies/${companyId}/action-plans/${plan.id}`:`/companies/${companyId}/action-plans`,json(plan?'PUT':'POST',{...form,notes:form.notes.trim()||null}));saved()}catch(e){setError((e as Error).message)}finally{setSaving(false)}};return <Modal title={plan?'Editar Plano de Ação':'Novo Plano de Ação'} close={close} wide>{error&&<div className="errorbar"><AlertCircle/>{error}</div>}<label>Problema identificado *<textarea autoFocus value={form.problem} onChange={e=>setForm({...form,problem:e.target.value})} placeholder="Descreva o problema ou situação identificada..."/></label><label>Ação proposta *<textarea value={form.proposedAction} onChange={e=>setForm({...form,proposedAction:e.target.value})} placeholder="Descreva o que será feito para resolver ou melhorar essa situação..."/></label><div className="two"><label>Prioridade *<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label><label>Responsável *<input value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})} placeholder="Nome do responsável"/></label></div>{plan&&<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})}>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}<label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Informações adicionais (opcional)"/></label><div className="modal-actions"><button onClick={close}>Cancelar</button><button className="primary" disabled={saving||!valid} onClick={save}>{saving?'Salvando...':plan?'Salvar alterações':'Criar Plano de Ação'}</button></div></Modal>}
function Detail({plan,close}:{plan:Plan;close:()=>void}){return <Modal title="Detalhes do Plano de Ação" close={close} wide><div className="action-detail"><div><span className={`priority-badge ${plan.priority}`}><i/>{priorityLabels[plan.priority]}</span><span className={`action-status ${plan.status}`}>{statusLabels[plan.status]}</span>{plan.overdue&&<span className="overdue-badge">Prazo vencido</span>}</div><Field label="Problema identificado" value={plan.problem}/><Field label="Ação proposta" value={plan.proposed_action}/><div className="detail-pairs"><Field label="Responsável" value={plan.responsible}/>{plan.due_date&&<Field label="Prazo" value={date(plan.due_date)}/>}<Field label="Diagnóstico" value={plan.diagnostic_name}/></div><Field label="Observações" value={plan.notes||'Nenhuma observação.'}/></div></Modal>}
function Field({label,value}:{label:string;value:string}){return <section><small>{label}</small><p>{value}</p></section>}
function Confirm({plan,close,remove}:{plan:Plan;close:()=>void;remove:()=>void}){return <Modal title="Excluir Plano de Ação?" close={close}><div className="delete-warning"><Trash2/><p>Essa ação será removida permanentemente.</p><small>{plan.problem}</small></div><div className="modal-actions"><button onClick={close}>Cancelar</button><button className="delete-button" onClick={remove}>Excluir</button></div></Modal>}
function Modal({title,close,children,wide=false}:{title:string;close:()=>void;children:any;wide?:boolean}){return <div className="action-modal-back" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className={`action-modal ${wide?'wide':''}`}><header><h3>{title}</h3><button onClick={close}><X/></button></header><div className="action-modal-body">{children}</div></div></div>}
function date(value:string){return new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo'}).format(new Date(value.length===10?`${value}T12:00:00-03:00`:value))}
