import { useEffect,useMemo,useState } from 'react';
import { ArrowRight,Building2,Plus,Search,X,Users,RefreshCw } from 'lucide-react';
import { api,json } from './api';

export type Company={id:string;name:string;trade_name?:string;approximate_employee_count?:number;notes?:string;active:boolean;diagnostic_count:number};

export function CompanyHub({onOpen,dbStatus}:{onOpen:(company:Company)=>void;dbStatus:'checking'|'ok'|'offline'}){
 const [items,setItems]=useState<Company[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[error,setError]=useState(''),[form,setForm]=useState({name:'',tradeName:'',approximateEmployeeCount:'',notes:'',active:true});
 const load=()=>{setLoading(true);api<Company[]>('/companies').then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[]);
 const filtered=useMemo(()=>items.filter(x=>(x.name+' '+(x.trade_name||'')).toLowerCase().includes(query.toLowerCase())),[items,query]);
 const save=async()=>{try{await api('/companies',json('POST',{...form,approximateEmployeeCount:form.approximateEmployeeCount?Number(form.approximateEmployeeCount):null}));setOpen(false);setForm({name:'',tradeName:'',approximateEmployeeCount:'',notes:'',active:true});load()}catch(e){setError((e as Error).message)}};
 return <div className="company-hub"><header><div className="hub-brand"><div className="brandmark">C</div><div><strong>Clima</strong><span>Diagnóstico organizacional</span></div></div><div className={`db ${dbStatus}`}><i/>{dbStatus==='ok'?'Banco conectado':dbStatus==='checking'?'Verificando banco':'Banco indisponível'}</div></header><main><div className="hub-title"><div><span>PORTAL DE EMPRESAS</span><h1>Selecione uma empresa</h1><p>Entre no ambiente da organização para gerenciar diagnósticos, entrevistas e resultados.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus/> Nova empresa</button></div><div className="hub-tools"><Search/><input aria-label="Buscar empresa" placeholder="Buscar por nome ou nome fantasia" value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} empresa{filtered.length===1?'':'s'}</span></div>{error&&<div className="errorbar">{error}<button onClick={()=>setError('')}><X/></button></div>}{loading?<div className="hub-empty"><RefreshCw className="spin"/><h2>Carregando empresas</h2></div>:!filtered.length?<div className="hub-empty"><Building2/><h2>{query?'Nenhuma empresa encontrada':'Cadastre a primeira empresa'}</h2><p>{query?'Tente outro termo de busca.':'Depois, você poderá criar diagnósticos semestrais dentro dela.'}</p></div>:<div className="company-grid">{filtered.map(x=><button className="company-card" key={x.id} onClick={()=>onOpen(x)}><div className="company-card-top"><div className="company-logo"><Building2/></div><i className={`pill ${x.active?'active':'archived'}`}>{x.active?'Ativa':'Inativa'}</i></div><h2>{x.trade_name||x.name}</h2>{x.trade_name&&<p>{x.name}</p>}<div className="company-stats"><span><Users/><b>{x.approximate_employee_count??'—'}</b> colaboradores</span><span><RefreshCw/><b>{x.diagnostic_count}</b> diagnósticos</span></div><footer>Entrar na empresa <ArrowRight/></footer></button>)}</div>}</main>{open&&<div className="hub-modal-back"><div className="hub-modal"><div><h2>Nova empresa</h2><button onClick={()=>setOpen(false)}><X/></button></div><label>Razão social / nome<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Nome fantasia<input value={form.tradeName} onChange={e=>setForm({...form,tradeName:e.target.value})}/></label><label>Quantidade aproximada de colaboradores<input type="number" value={form.approximateEmployeeCount} onChange={e=>setForm({...form,approximateEmployeeCount:e.target.value})}/></label><label>Observações<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary full" disabled={!form.name.trim()} onClick={save}>Salvar empresa</button></div></div>}</div>
}
