import { useEffect,useMemo,useState } from 'react';
import { BarChart3,CheckCircle2,Download,FileText,LockKeyhole,Presentation,RefreshCw,ShieldCheck,Users } from 'lucide-react';
import { api } from './api';

type Props={diagnosticId:string};
type Person={id:string;name:string;role:'leader'|'director';evaluation_count:number;available:boolean};
type Options={minimumSampleSize:number;people:Person[]};

export function Reports({diagnosticId}:Props){
 const [type,setType]=useState<'general'|'leadership'>('general'),[options,setOptions]=useState<Options>(),[personId,setPersonId]=useState(''),[includeComments,setIncludeComments]=useState(true),[loading,setLoading]=useState(true),[exporting,setExporting]=useState<'pdf'|'pptx'>(),[error,setError]=useState('');
 useEffect(()=>{setLoading(true);setError('');api<Options>(`/diagnostics/${diagnosticId}/reports/options`).then(x=>{setOptions(x);setPersonId(x.people.find(p=>p.available)?.id||'')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[diagnosticId]);
 const selected=useMemo(()=>options?.people.find(x=>x.id===personId),[options,personId]),blocked=type==='leadership'&&!selected?.available;
 const download=async(format:'pdf'|'pptx')=>{if(blocked)return;setExporting(format);setError('');try{const response=await fetch(`/api/diagnostics/${diagnosticId}/reports/export?format=${format}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,personId:type==='leadership'?personId:undefined,includeComments})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||'Não foi possível gerar o relatório.')}const blob=await response.blob(),header=response.headers.get('Content-Disposition')||'',name=header.match(/filename="([^"]+)"/)?.[1]||`relatorio.${format}`,url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(e){setError((e as Error).message)}finally{setExporting(undefined)}};
 if(loading)return <div className="report-state"><RefreshCw className="spin"/><h2>Preparando relatórios</h2><p>Verificando dados e critérios de privacidade.</p></div>;
 return <div className="reports-page"><div className="report-heading"><div><span>EXPORTAÇÃO SEGURA</span><h2>Central de relatórios</h2><p>Gere documentos claros e prontos para apresentação, respeitando o anonimato configurado.</p></div><div className="report-privacy"><ShieldCheck/><div><b>Privacidade aplicada</b><small>Amostra mínima: {options?.minimumSampleSize||'—'} avaliações</small></div></div></div>{error&&<div className="errorbar">{error}</div>}<div className="report-type-grid"><button className={type==='general'?'active':''} onClick={()=>setType('general')}><span><BarChart3/></span><div><b>Relatório geral</b><p>Visão consolidada para empresa e diretoria, sem identificação individual.</p></div>{type==='general'&&<CheckCircle2/>}</button><button className={type==='leadership'?'active':''} onClick={()=>setType('leadership')}><span><Users/></span><div><b>Relatório de liderança</b><p>Documento confidencial e exclusivo para a liderança selecionada.</p></div>{type==='leadership'&&<CheckCircle2/>}</button></div><div className="report-workspace"><section className="report-settings"><h3>Configurar relatório</h3>{type==='leadership'&&<label>Liderança<select value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Selecione uma liderança</option>{options?.people.map(p=><option value={p.id} key={p.id} disabled={!p.available}>{p.name} · {p.evaluation_count} avaliações{!p.available?' · bloqueado':''}</option>)}</select></label>}<label className="report-check"><input type="checkbox" checked={includeComments} onChange={e=>setIncludeComments(e.target.checked)}/><span/><div><b>Incluir comentários anônimos</b><small>Somente trechos sem identificação e dentro da regra de amostra mínima.</small></div></label>{type==='leadership'&&selected&&!selected.available&&<div className="report-blocked"><LockKeyhole/><div><b>Relatório bloqueado</b><p>Esta liderança possui {selected.evaluation_count} avaliações. São necessárias {options?.minimumSampleSize} para proteger o anonimato.</p></div></div>}<div className="report-downloads"><button disabled={!!exporting||blocked} onClick={()=>download('pdf')}><FileText/>{exporting==='pdf'?<><RefreshCw className="spin"/> Gerando PDF...</>:<>Baixar PDF</>}</button><button className="primary" disabled={!!exporting||blocked||type==='leadership'&&!personId} onClick={()=>download('pptx')}><Presentation/>{exporting==='pptx'?<><RefreshCw className="spin"/> Gerando...</>:<>Apresentação editável</>}</button></div><p className="canva-note"><Download/> O arquivo PPTX pode ser importado no Canva e editado como apresentação.</p></section><ReportPreview type={type} person={selected} includeComments={includeComments}/></div></div>
}

function ReportPreview({type,person,includeComments}:{type:'general'|'leadership';person?:Person;includeComments:boolean}){const general=['Resumo executivo','Participação e favorabilidade','Resultado por categoria','Agrupadores recorrentes',...(includeComments?['Comentários selecionados']:[]),'Plano de ação'],leadership=['Resumo individual protegido','Resultado por pergunta','Pontos fortes e atenção','Agrupadores da liderança',...(includeComments?['Comentários anônimos']:[])];const sections=type==='general'?general:leadership;return <section className="report-preview"><div className="preview-cover"><i>C</i><span>{type==='general'?'RELATÓRIO GERAL':'RELATÓRIO CONFIDENCIAL'}</span><h3>{type==='general'?'Diagnóstico organizacional':person?.name||'Selecione uma liderança'}</h3><p>Documento executivo · Visual 16:9 e PDF A4</p><small><ShieldCheck/> Critérios de privacidade aplicados</small></div><div className="preview-sections"><b>Conteúdo do relatório</b>{sections.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p><CheckCircle2/></div>)}</div></section>}
